#!/usr/bin/env python3
"""Build fidelity_report.md from line_audit.csv + first_false.csv."""
import csv, glob, os, re, statistics
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
rows = list(csv.DictReader(open(os.path.join(HERE, 'line_audit.csv'))))
firsts = list(csv.DictReader(open(os.path.join(HERE, 'first_false.csv'))))

# greedy accuracy context
ngold = 0
for f in glob.glob(os.path.join(HERE, 'r8_val_transcripts', '*.txt')):
    txt = open(f).read()
    gold = re.search(r"gold=(\S+)", txt).group(1)
    out = txt.split('## OUTPUT', 1)[1]
    bx = re.findall(r"\\boxed\{(.*?)\}", out)
    if bx and bx[-1] == gold:
        ngold += 1

agg = defaultdict(lambda: [0, [0, 0], [0, 0], [0, 0]])
for r in rows:
    k = f"{r['type']}/{r['family']}" if r['family'] else r['type']
    a = agg[k]
    a[0] += 1
    for i, c in ((1, 'transcription'), (2, 'arithmetic'), (3, 'verdict')):
        if r[c] != '':
            a[i][1] += 1
            a[i][0] += int(r[c])

def pct(x):
    return f'{100*x[0]/x[1]:.1f}' if x[1] else '-'

L = []
L.append('# crypt-boot-r8 per-line fidelity audit (100 held-out val transcripts)')
L.append('')
L.append('Generated by `analysis/crypt_fidelity/line_audit.py` -> `line_audit.csv`'
         ' (7,566 line records), `first_false.csv`.')
L.append('')
L.append(f'Context: greedy boxed == gold on {ngold}/100 transcripts. '
         'Axes per line: T transcription (glyphs/numbers copied from prompt or '
         'earlier trace), A arithmetic (every visible computation recomputed), '
         'V verdict (does the stated conclusion follow from the line\'s OWN '
         'numbers). "-" = axis not applicable / not mechanically checkable.')
L.append('')
L.append('## (a) Fidelity table')
L.append('')
L.append('| line type | n | T ok% (nT) | A ok% (nA) | V ok% (nV) |')
L.append('|---|---|---|---|---|')
for k in sorted(agg, key=lambda k: -agg[k][0]):
    n, T, A, V = agg[k]
    L.append(f'| {k} | {n} | {pct(T)} ({T[1]}) | {pct(A)} ({A[1]}) | {pct(V)} ({V[1]}) |')
L.append('')

L.append('## (b) First-false-line distribution (per transcript)')
L.append('')
cnt = Counter()
for f in firsts:
    if f['type']:
        k = f"{f['type']}/{f['family']}" if f['family'] else f['type']
        cnt[(k, f['axis'])] += 1
L.append('| first false line | axis | transcripts |')
L.append('|---|---|---|')
for (k, ax), c in cnt.most_common():
    L.append(f'| {k} | {ax} | {c} |')
nclean = sum(1 for f in firsts if not f['type'])
L.append(f'| (no false line) | - | {nclean} |')
L.append('')

# (c) executable atoms
L.append('## (c) Executable-atom list (all checked axes >= 99%, n >= 30)')
L.append('')
atoms, consts = [], []
for k in sorted(agg, key=lambda k: -agg[k][0]):
    n, T, A, V = agg[k]
    if n < 30:
        continue
    checked = [x for x in (T, A, V) if x[1] > 0]
    if not checked:
        consts.append((k, n))
        continue
    if all(100 * x[0] / x[1] >= 99 for x in checked):
        atoms.append((k, n, pct(T), pct(A), pct(V)))
for k, n, t, a, v in atoms:
    L.append(f'- **{k}** (n={n}; T {t} / A {a} / V {v})')
L.append('')
if consts:
    L.append('Content-free constant lines (n >= 30, nothing checkable; trivially '
             'reproduced): ' + ', '.join(f'{k} (n={n})' for k, n in consts))
L.append('')

# (d) kill list
L.append('## (d) Kill-list (verdict axis < 90%)')
L.append('')
L.append('| line type | n | V ok% | nV |')
L.append('|---|---|---|---|')
for k in sorted(agg, key=lambda k: (100*agg[k][3][0]/agg[k][3][1]) if agg[k][3][1] else 999):
    n, T, A, V = agg[k]
    if V[1] and 100 * V[0] / V[1] < 90:
        L.append(f'| {k} | {n} | {pct(V)} | {V[1]} |')
L.append('')

# (e) verbatim examples of the most common verdict failure
L.append('## (e) The most common verdict failure: ones-residue enumeration that '
         'STATES a matching pair and concludes "none matches"')
L.append('')
ex = [r for r in rows if r['type'] == 'kill' and r['family'] in ('onesenum', '2mode', 'modekill')
      and r['verdict'] == '0' and 'match the target' in r['note']]
seen_ids, picked = set(), []
for r in ex:
    if r['id'] not in seen_ids:
        picked.append(r)
        seen_ids.add(r['id'])
    if len(picked) == 3:
        break
for r in picked:
    L.append(f'- `{r["id"]}` | `{r["text"]}`')
    L.append(f'  - checker: {r["note"]}')
L.append('')
L.append('## Checker semantics / caveats (for reading the table honestly)')
L.append('')
L.append('- Domain references (`X in {..}`, enumd pre-domains, eliml free sets) are '
         'checked with SUBSET semantics against a conservative tracked state '
         '(10 digits minus visible pins/exclusions, minus 0 for leading letters): '
         'a stated domain narrower than tracked is accepted (engine-style '
         'narrowing is not always visible), wider = transcription fail. So the '
         'T numbers for kill/pin witnesses are an UPPER bound on copy fidelity.')
L.append('- Range-kill bounds are checked for SOUNDNESS (a true bound), matching the '
         'renderer\'s sound-interval bounds; a true-but-non-killing bound (e.g. '
         '`|a-b| <= 89` against a 2-digit target) fails only the VERDICT axis. '
         'kill/range A=97.1 vs V=51.0 means: bounds are real arithmetic, but half '
         'the range-kill conclusions do not follow from them.')
L.append('- kill/sign V=100 but T=95.1: the sign-vs-glyph logic itself is always '
         'applied correctly, but in ~5% of lines the model picks/claims an example '
         'equation whose RHS does NOT have the stated sign property (fabricated '
         'premise -> transcription fail, verdict vacuously consistent).')
L.append('- bail/stall-interchangeable T=0/70 is dominated by 2 degenerate-loop '
         'transcripts that re-guess an already-pinned symbol dozens of times '
         '(s36..s105 identical lines); it is a loop pathology, not 70 independent '
         'errors.')
L.append('- Exactly 1 of the 100 prompts (1d15b7e6) has a true op-glyph/digit-glyph '
         'overlap (`@`), which the r8 grammar never taught; its union/disjoint '
         'fails are charged to the model in this table.')
L.append('- try-counter rows are the sN counters audited as their own one-check '
         'records (monotone +1); 2365/2365 correct.')
L.append('- `verify()`-level note: greedy boxed == gold on only 4/100, consistent '
         'with eval_oracle\'s ~.05.')
L.append('')

# (f) tokens
toks = sorted(int(f['tokens_before']) for f in firsts if f['type'])
L.append('## (f) Tokens consumed before the first false line')
L.append('')
L.append(f'- median **{statistics.median(toks):.0f}** tokens (p25 {toks[len(toks)//4]}, '
         f'p75 {toks[3*len(toks)//4]}, min {toks[0]}, max {toks[-1]}) over the '
         f'{len(toks)} transcripts that contain a false line; {nclean} transcripts '
         'have no false line at all.')
L.append('')

open(os.path.join(HERE, 'fidelity_report.md'), 'w').write('\n'.join(L) + '\n')
print('\n'.join(L[:8]))
print('... report written to fidelity_report.md')
print('atoms:', [a[0] for a in atoms])
